- name: Adds vbernat PPA
  apt_repository: repo=ppa:vbernat/haproxy-1.5 state=present

- name: Installs haproxy
  apt: pkg=haproxy state=installed update_cache=yes
  register: __haproxy_installed

- name: Installs haptop
  apt: pkg=hatop state=latest
  when: haproxy_install_hatop

- name: Adds default config
  template: src='../templates/haproxy.cfg.j2' dest=/etc/haproxy/haproxy.cfg
  notify: Restart haproxy-multi
  tags:
    - config
    - haproxy:config

- name: Adds multi-startup script
  template:
    src: '../templates/haproxy.debian-multi.init.j2'
    dest: /etc/init.d/haproxy-multi
      mode: 700
  notify: Restart haproxy-multi
  when: "not {{ haproxy_use_pacemaker }}"

- name: Adds pacemaker OCF if pacemaker is used
  template:
    src: templates/haproxy.ocf.j2
    dest: /usr/lib/ocf/resource.d/heartbeat/haproxy
    mode: 0755
  when: "not {{ haproxy_use_pacemaker }}"

- name: Creates config fragments directory
  file: path=/etc/haproxy/conf.d state=directory
  notify: Restart haproxy-multi

- name: Enables multi init script if pacemaker is disabled
  service: name=haproxy-multi enabled={{ ! haproxy_use_pacemaker }}

- name: Disables stock init script
  service: name=haproxy enabled=no
  changed_when: false
  when: __haproxy_installed|changed

- name: Stop current haproxy
  service: name=haproxy state=stopped
  when: __haproxy_installed|changed
  notify: Restart haproxy-multi

- name: Removes stock init script
  file:
    path: /etc/init.d/haproxy
    state: absent
