# We do not restart if we use pacemaker
- name: Restart haproxy-multi
  service: name=haproxy-multi state=restarted
  notify: Check that haproxy runs
  when: "not {{ haproxy_use_pacemaker }}"

- name: Check that haproxy runs 
  shell: ps auwx | grep `cat /var/run/haproxy.pid` | grep haproxy
